---
title: Sva Ixd Thesis
timezone: UTC
collections:
  ideas:
    title: Ideas
    output: false
    permalink: "/project/:path/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: drafts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: projects
  values:
    layout: default
permalink: "/:year/:month/:day/:title/"
baseurl: "/sva-ixd-thesis"
sass:
  sass_dir: _scss
  style: compressed
